name: Frontend CI - Build & Push Image

on:
  # Manual trigger
  workflow_dispatch:

  # Automatic trigger on pushes to the main branch
  push:
    branches:
      - main
    paths: # Only trigger if changes are in the frontend directory or this file
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

# Define environment variables for all jobs
env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_NAME }}.azurecr.io

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/frontend:${{ github.sha }} ./frontend/
          docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:${{ github.sha }}

      - name: Logout from Azure
        if: always() # This step runs even if the job fails
        run: az logout