name: CD - Deploy Frontend to AKS

on:
  workflow_dispatch:
    inputs:
      aks_cluster_name:
        description: 'Name of the AKS Cluster to deploy to'
        required: true
      aks_resource_group:
        description: 'Resource Group of the AKS Cluster'
        required: true

# Define environment variables for all jobs
env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_NAME }}.azurecr.io

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        run: az acr login --name ${{ secrets.ACR_NAME }}

      # Note: This workflow assumes the image was already built and pushed by the CI pipeline.
      # This CD pipeline's job is to deploy the Kubernetes manifests.

      - name: Set Kubernetes context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ github.event.inputs.aks_resource_group }}
          cluster-name: ${{ github.event.inputs.aks_cluster_name }}
      
      - name: Replace image tag in Kubernetes manifest
        run: |
          sed -i "s|/frontend:.*|/frontend:${{ github.sha }}|g" k8s/frontend.yaml
          echo "--- Modified frontend.yaml content ---"
          cat k8s/frontend.yaml
          echo "---------------------------------"

      - name: Deploy Frontend to AKS
        run: |
          echo "Deploying frontend to AKS cluster: ${{ github.event.inputs.aks_cluster_name }}"
          kubectl apply -f k8s/frontend.yaml

      - name: Logout from Azure
        if: always()
        run: az logout